// Barril del UI kit. Importa desde aquí: `import { Button, Card } from '../ui'`.

export { Button } from './Button'
export { FileButton } from './FileButton'
export { Input } from './Input'
export { Field } from './Field'
export { Card } from './Card'
export { Modal } from './Modal'
export { Lightbox } from './Lightbox'
export { Badge } from './Badge'
export { Spinner } from './Spinner'
export { Skeleton } from './Skeleton'
export { CountUp } from './CountUp'
export { ScoreRing } from './ScoreRing'
export { CountdownRing } from './CountdownRing'
export { Stack } from './Stack'
export { Row } from './Row'
export { ToastProvider } from './ToastProvider'
export { useToast } from './toast-context'
export type { ToastApi, ToastOptions, ToastTone } from './toast-context'
export { withViewTransition, useReducedMotion } from './motion'
export { Icon } from './Icon'

// Pantallas y piezas de "Cuentas + Home" (presentacionales; las cablean #3/#4/#5).
export { Avatar } from './Avatar'
export { GroupCard } from './GroupCard'
export type { GroupStatus } from './GroupCard'
export { CreateGroupFab } from './CreateGroupFab'
export { BackHomeButton } from './BackHomeButton'
export { ChallengePhoto } from './ChallengePhoto'
export { PhotoStrip } from './PhotoStrip'
export type { PhotoStripItem } from './PhotoStrip'
export { HomeEmptyState } from './HomeEmptyState'
export { HowItWorks } from './HowItWorks'
export { HomeDashboard } from './HomeDashboard'
export type { HomeGroup } from './HomeDashboard'
export { AuthScreen } from './AuthScreen'
export { LoginScreen } from './LoginScreen'
export { CheckEmail } from './CheckEmail'
export { EnterCode } from './EnterCode'
export { ProfileStep } from './ProfileStep'

// Estados vacíos y de carga reutilizables (issue #156).
export { EmptyState } from './EmptyState'
export { SkeletonCard } from './SkeletonCard'
